-- ============================================================
-- 01_data_validation.sql
-- Project: Purchase-to-Pay Process Mining & Exception Intelligence
-- Database: MySQL 8.0+
-- Purpose:
--   1. Create a raw staging table for the converted BPI 2019 CSV
--   2. Validate row counts, analytical grain, activities and nulls
--   3. Investigate timestamps, duplicate-looking rows and case fields
--
-- IMPORTANT:
--   Do not delete or deduplicate source records in this script.
-- ============================================================

CREATE DATABASE IF NOT EXISTS p2p;
USE p2p;

DROP TABLE IF EXISTS p2p_events_raw;

CREATE TABLE p2p_events_raw (
    event_id                         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id                          VARCHAR(255),
    org_resource                     VARCHAR(255),
    activity                         VARCHAR(255),
    cumulative_net_worth_eur         DECIMAL(20,4),

    -- Keep the original timestamp text because the CSV may contain
    -- timezone suffixes. The generated DATETIME uses the first
    -- YYYY-MM-DD HH:MM:SS portion for repeatable analysis.
    event_timestamp_raw              VARCHAR(64),
    event_timestamp                  DATETIME
        GENERATED ALWAYS AS (
            STR_TO_DATE(
                REPLACE(LEFT(event_timestamp_raw, 19), 'T', ' '),
                '%Y-%m-%d %H:%i:%s'
            )
        ) STORED,

    spend_area                       VARCHAR(255),
    company                          VARCHAR(255),
    document_type                    VARCHAR(255),
    sub_spend_area                   VARCHAR(255),
    purchasing_document              VARCHAR(255),
    purchasing_document_category     VARCHAR(255),
    vendor                           VARCHAR(255),
    item_type                        VARCHAR(255),
    item_category                    VARCHAR(255),
    spend_classification             VARCHAR(255),
    source_system                    VARCHAR(255),
    case_name                        VARCHAR(500),
    gr_based_invoice_verification    VARCHAR(255),
    item                             VARCHAR(255),
    case_id                          VARCHAR(255),
    goods_receipt                    VARCHAR(255),

    PRIMARY KEY (event_id),
    INDEX idx_raw_case_id (case_id),
    INDEX idx_raw_activity (activity),
    INDEX idx_raw_timestamp (event_timestamp),
    INDEX idx_raw_vendor (vendor)
);

-- ============================================================
-- CSV IMPORT
-- ============================================================
-- Recommended for MySQL Workbench:
-- Server > Data Import / Table Data Import Wizard, or use
-- LOAD DATA LOCAL INFILE after changing the path below.
--
-- IMPORTANT:
-- The CSV has 21 source columns. event_id and event_timestamp are
-- generated by MySQL and therefore are NOT listed in the import map.
--
-- Example:
--
-- SET GLOBAL local_infile = 1;
--
-- LOAD DATA LOCAL INFILE 'C:/path/to/output.csv'
-- INTO TABLE p2p_events_raw
-- CHARACTER SET utf8mb4
-- FIELDS TERMINATED BY ','
-- OPTIONALLY ENCLOSED BY '"'
-- LINES TERMINATED BY '\n'
-- IGNORE 1 LINES
-- (
--   user_id,
--   org_resource,
--   activity,
--   cumulative_net_worth_eur,
--   event_timestamp_raw,
--   spend_area,
--   company,
--   document_type,
--   sub_spend_area,
--   purchasing_document,
--   purchasing_document_category,
--   vendor,
--   item_type,
--   item_category,
--   spend_classification,
--   source_system,
--   case_name,
--   gr_based_invoice_verification,
--   item,
--   case_id,
--   goods_receipt
-- );
--
-- If your file uses Windows CRLF line endings and the import creates
-- trailing carriage returns, change LINES TERMINATED BY '\n' to '\r\n'.
-- ============================================================


-- ============================================================
-- 1. SOURCE BASELINE
-- Expected from the validated project source:
--   Event rows            : 1,595,923
--   Unique P2P cases      :   251,734
--   Purchasing documents  :    76,349
--   Vendors               :     1,975
--   Activities            :        42
--   Companies             :         4
-- ============================================================

SELECT
    COUNT(*) AS event_rows,
    COUNT(DISTINCT case_id) AS unique_cases,
    COUNT(DISTINCT purchasing_document) AS purchasing_documents,
    COUNT(DISTINCT vendor) AS vendors,
    COUNT(DISTINCT activity) AS activities,
    COUNT(DISTINCT company) AS companies
FROM p2p_events_raw;


-- ============================================================
-- 2. EVENT-LEVEL VS CASE-LEVEL GRAIN
-- ============================================================

SELECT
    case_id,
    COUNT(*) AS event_count
FROM p2p_events_raw
GROUP BY case_id
ORDER BY event_count DESC
LIMIT 20;

WITH events_per_case AS (
    SELECT
        case_id,
        COUNT(*) AS event_count
    FROM p2p_events_raw
    GROUP BY case_id
),
ranked AS (
    SELECT
        event_count,
        CUME_DIST() OVER (ORDER BY event_count) AS cumulative_share
    FROM events_per_case
)
SELECT
    MIN(event_count) AS min_events,
    ROUND(AVG(event_count), 2) AS avg_events,
    MIN(CASE WHEN cumulative_share >= 0.50 THEN event_count END) AS median_events,
    MIN(CASE WHEN cumulative_share >= 0.90 THEN event_count END) AS p90_events,
    MIN(CASE WHEN cumulative_share >= 0.95 THEN event_count END) AS p95_events,
    MIN(CASE WHEN cumulative_share >= 0.99 THEN event_count END) AS p99_events,
    MAX(event_count) AS max_events
FROM ranked;


-- ============================================================
-- 3. ACTIVITY INVENTORY
-- ============================================================

SELECT
    activity,
    COUNT(*) AS event_count,
    COUNT(DISTINCT case_id) AS case_count,
    ROUND(
        100.0 * COUNT(*) /
        (SELECT COUNT(*) FROM p2p_events_raw),
        2
    ) AS event_share_pct,
    ROUND(
        100.0 * COUNT(DISTINCT case_id) /
        (SELECT COUNT(DISTINCT case_id) FROM p2p_events_raw),
        2
    ) AS case_share_pct
FROM p2p_events_raw
GROUP BY activity
ORDER BY event_count DESC;


-- ============================================================
-- 4. NULL PROFILE
-- ============================================================

SELECT
    COUNT(*) AS total_rows,
    SUM(user_id IS NULL) AS user_id_nulls,
    SUM(org_resource IS NULL) AS org_resource_nulls,
    SUM(activity IS NULL) AS activity_nulls,
    SUM(cumulative_net_worth_eur IS NULL) AS value_nulls,
    SUM(event_timestamp_raw IS NULL OR event_timestamp IS NULL) AS timestamp_nulls,
    SUM(spend_area IS NULL) AS spend_area_nulls,
    SUM(company IS NULL) AS company_nulls,
    SUM(document_type IS NULL) AS document_type_nulls,
    SUM(sub_spend_area IS NULL) AS sub_spend_area_nulls,
    SUM(purchasing_document IS NULL) AS purchasing_document_nulls,
    SUM(purchasing_document_category IS NULL) AS purchasing_category_nulls,
    SUM(vendor IS NULL) AS vendor_nulls,
    SUM(item_type IS NULL) AS item_type_nulls,
    SUM(item_category IS NULL) AS item_category_nulls,
    SUM(spend_classification IS NULL) AS spend_classification_nulls,
    SUM(source_system IS NULL) AS source_system_nulls,
    SUM(case_name IS NULL) AS case_name_nulls,
    SUM(gr_based_invoice_verification IS NULL) AS gr_based_inv_nulls,
    SUM(item IS NULL) AS item_nulls,
    SUM(case_id IS NULL) AS case_id_nulls,
    SUM(goods_receipt IS NULL) AS goods_receipt_nulls
FROM p2p_events_raw;


-- ============================================================
-- 5. TIMESTAMP VALIDATION
-- ============================================================

SELECT
    MIN(event_timestamp) AS min_timestamp,
    MAX(event_timestamp) AS max_timestamp,
    SUM(event_timestamp IS NULL) AS unparsable_timestamp_rows
FROM p2p_events_raw;

SELECT
    YEAR(event_timestamp) AS event_year,
    COUNT(*) AS event_count,
    COUNT(DISTINCT case_id) AS case_count
FROM p2p_events_raw
GROUP BY YEAR(event_timestamp)
ORDER BY event_year;

SELECT
    case_id,
    activity,
    event_timestamp_raw,
    event_timestamp,
    vendor,
    purchasing_document
FROM p2p_events_raw
WHERE event_timestamp < '2016-01-01'
ORDER BY event_timestamp, event_id
LIMIT 200;


-- ============================================================
-- 6. DUPLICATE-LOOKING ROWS
-- ============================================================
-- Identical visible records are NOT automatically removed because
-- repeated business events may be legitimate.

WITH duplicate_groups AS (
    SELECT
        user_id,
        org_resource,
        activity,
        cumulative_net_worth_eur,
        event_timestamp_raw,
        spend_area,
        company,
        document_type,
        sub_spend_area,
        purchasing_document,
        purchasing_document_category,
        vendor,
        item_type,
        item_category,
        spend_classification,
        source_system,
        case_name,
        gr_based_invoice_verification,
        item,
        case_id,
        goods_receipt,
        COUNT(*) AS duplicate_count
    FROM p2p_events_raw
    GROUP BY
        user_id,
        org_resource,
        activity,
        cumulative_net_worth_eur,
        event_timestamp_raw,
        spend_area,
        company,
        document_type,
        sub_spend_area,
        purchasing_document,
        purchasing_document_category,
        vendor,
        item_type,
        item_category,
        spend_classification,
        source_system,
        case_name,
        gr_based_invoice_verification,
        item,
        case_id,
        goods_receipt
    HAVING COUNT(*) > 1
)
SELECT
    COUNT(*) AS duplicate_groups,
    SUM(duplicate_count - 1) AS extra_duplicate_looking_rows
FROM duplicate_groups;

WITH duplicate_groups AS (
    SELECT
        activity,
        case_id,
        event_timestamp_raw,
        org_resource,
        purchasing_document,
        item,
        COUNT(*) AS duplicate_count
    FROM p2p_events_raw
    GROUP BY
        activity,
        case_id,
        event_timestamp_raw,
        org_resource,
        purchasing_document,
        item
    HAVING COUNT(*) > 1
)
SELECT
    activity,
    COUNT(*) AS duplicate_groups,
    SUM(duplicate_count - 1) AS extra_rows
FROM duplicate_groups
GROUP BY activity
ORDER BY extra_rows DESC;


-- ============================================================
-- 7. USER VS ORG_RESOURCE VALIDATION
-- ============================================================

SELECT
    COUNT(*) AS total_rows,
    SUM(user_id <=> org_resource) AS matching_rows,
    SUM(NOT (user_id <=> org_resource)) AS non_matching_rows,
    ROUND(
        100.0 * SUM(user_id <=> org_resource) / COUNT(*),
        4
    ) AS matching_pct
FROM p2p_events_raw;


-- ============================================================
-- 8. CONSTANT / LOW-CARDINALITY FIELDS
-- ============================================================

SELECT
    COUNT(DISTINCT company) AS company_values,
    COUNT(DISTINCT purchasing_document_category) AS purchasing_category_values,
    COUNT(DISTINCT source_system) AS source_system_values,
    COUNT(DISTINCT item_category) AS item_category_values,
    COUNT(DISTINCT document_type) AS document_type_values,
    COUNT(DISTINCT gr_based_invoice_verification) AS gr_verification_values,
    COUNT(DISTINCT goods_receipt) AS goods_receipt_values
FROM p2p_events_raw;


-- ============================================================
-- 9. CASE-ATTRIBUTE CONSISTENCY
-- ============================================================

WITH case_checks AS (
    SELECT
        case_id,
        COUNT(DISTINCT vendor) AS vendor_values,
        COUNT(DISTINCT company) AS company_values,
        COUNT(DISTINCT purchasing_document) AS purchasing_document_values,
        COUNT(DISTINCT document_type) AS document_type_values,
        COUNT(DISTINCT item_type) AS item_type_values,
        COUNT(DISTINCT item_category) AS item_category_values,
        COUNT(DISTINCT spend_area) AS spend_area_values,
        COUNT(DISTINCT sub_spend_area) AS sub_spend_area_values,
        COUNT(DISTINCT spend_classification) AS spend_classification_values,
        COUNT(DISTINCT gr_based_invoice_verification) AS gr_verification_values,
        COUNT(DISTINCT goods_receipt) AS goods_receipt_values
    FROM p2p_events_raw
    GROUP BY case_id
)
SELECT
    SUM(vendor_values > 1) AS cases_with_multiple_vendors,
    SUM(company_values > 1) AS cases_with_multiple_companies,
    SUM(purchasing_document_values > 1) AS cases_with_multiple_documents,
    SUM(document_type_values > 1) AS cases_with_multiple_document_types,
    SUM(item_type_values > 1) AS cases_with_multiple_item_types,
    SUM(item_category_values > 1) AS cases_with_multiple_item_categories,
    SUM(spend_area_values > 1) AS cases_with_multiple_spend_areas,
    SUM(sub_spend_area_values > 1) AS cases_with_multiple_sub_spend_areas,
    SUM(spend_classification_values > 1) AS cases_with_multiple_spend_classes,
    SUM(gr_verification_values > 1) AS cases_with_multiple_gr_flags,
    SUM(goods_receipt_values > 1) AS cases_with_multiple_gr_values
FROM case_checks;


-- ============================================================
-- 10. MONETARY FIELD CONSISTENCY
-- ============================================================

WITH value_check AS (
    SELECT
        case_id,
        COUNT(DISTINCT cumulative_net_worth_eur) AS distinct_values,
        MIN(cumulative_net_worth_eur) AS min_value,
        MAX(cumulative_net_worth_eur) AS max_value
    FROM p2p_events_raw
    GROUP BY case_id
)
SELECT
    COUNT(*) AS total_cases,
    SUM(distinct_values > 1) AS cases_with_changing_value,
    ROUND(
        100.0 * SUM(distinct_values > 1) / COUNT(*),
        2
    ) AS changing_value_case_pct
FROM value_check;

WITH changing_cases AS (
    SELECT case_id
    FROM p2p_events_raw
    GROUP BY case_id
    HAVING COUNT(DISTINCT cumulative_net_worth_eur) > 1
)
SELECT
    e.case_id,
    e.event_timestamp,
    e.activity,
    e.cumulative_net_worth_eur
FROM p2p_events_raw e
JOIN changing_cases c
    ON e.case_id = c.case_id
ORDER BY e.case_id, e.event_timestamp, e.event_id
LIMIT 200;


-- ============================================================
-- 11. PROCESS-CATEGORY DISTRIBUTION
-- ============================================================

SELECT
    item_category,
    COUNT(DISTINCT case_id) AS cases,
    ROUND(
        100.0 * COUNT(DISTINCT case_id) /
        (SELECT COUNT(DISTINCT case_id) FROM p2p_events_raw),
        2
    ) AS case_share_pct
FROM p2p_events_raw
GROUP BY item_category
ORDER BY cases DESC;


-- ============================================================
-- END OF SOURCE VALIDATION
-- Next: 02_case_level_model.sql
-- ============================================================
